routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::resource('contacts','ContactController');
Route::get('/search', 'ContactController@search');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::all();
        return view('contacts.index', ['contacts' => $contacts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->except('_token');
        $contact = new Contact();
        foreach ($inputs as $key => $value) {
            $contact->$key = $value;
        }
        $contact->save();
    
        return redirect(route('contacts.index'))->with('success', 'Contact enregistré');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = Contact::find($id);
        return view('contacts.edit', ['contact' => $contact]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $inputs = $request->except('_token','_method');
        $contact = Contact::find($id);
        foreach ($inputs as $key => $value) {
            $contact->$key = $value;
        }
        $contact->save(); // sauvegarde les données insérées

        return redirect(route('contacts.index'))->with('success','Experience mis à jour');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();

        return redirect (route('contacts.index'))->with('sucess', 'Experience supprimée avec succès !');
    }

    public function search(Request $request)
    {
        // $search = $request->get('search');
        // $contacts = DB::table('contacts')->where('name', 'like', '%'.$search.'%')->paginate(5);
        // $contacts = DB::table('contacts')->where('lastname', 'like', '%'.$search.'%')->paginate(5);
        $contacts=Contact::all();
        return view('contacts.search', ['contacts'=>$contacts]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contacts/create.blade.php
@extends('template.app')

@section('title', 'Créer - Contact')

@section('contenu')
<div class="card">
    <div class="card-header">Créer un contact</div>
    <div class="card-content">
        <form class="form-material" method="POST" action="{{route('contacts.store')}}">
            @csrf
            <div class="grix xs1">
                <div class="form-field">
                    <input type="text" id="name" name="name" class="form-control" />
                    <label for="title">Name</label>
                </div>
                <div class="form-field">
                    <label for="lastname">Lastname</label>
                    <textarea id="lastname" name="lastname" class="form-control"></textarea> 
                </div>
                <div class="form-field">
                    <label for="phone">Phone</label>
                    <textarea id="phone" name="phone" class="form-control"></textarea> 
                </div>
                <div class="form-field">
                    <label for="email">Email</label>
                    <textarea id="email" name="email" class="form-control"></textarea> 
                </div>
            </div>
            <button type="submit" class="btn press primary">Créer</button>
        </form>
    </div>
</div>
@endsection

resources/views/contacts/edit.blade.php
@extends('template.app')

@section('title', 'Editer - Contact')

@section('contenu')
<div class="card">
    <div class="card-header">Editer une contact</div>
    <div class="card-content">
        <form class="form-material" method="POST" action="{{route('contacts.update', ['contact' => $contact->id])}}">
            @method('PUT')
            @csrf
            <div class="grix xs1">
                <div class="form-field">
                    <input type="text" id="name" name="name" class="form-control" value="{{$contact->name}}" />
                    <label for="title">Name</label>
                </div>
                <div class="form-field">
                    <label for="lastname">Lastname</label>
                    <textarea id="lastname" name="lastname" class="form-control">{{$contact->lastname}}</textarea>
                </div>
            </div>
            <button type="submit" class="btn press secondary">Modifier</button>
        </form>
    </div>
</div>
@endsection

resources/views/contacts/index.blade.php
@extends('template.app')

@section('title', 'Mes contacts')

@section('contenu')
<div class="responsive-table">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>LastName</th>
                <th>Phone</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach($contacts as $contact)
            <tr>
                <td>{{$contact->id}}</td>
                <td>{{$contact->name}}</td>
                <td>{{$contact->lastname}}</td>
                <td>{{$contact->phone}}</td>
                <td>{{$contact->email}}</td>
                <td>
                <a href="{{route('contacts.edit', ['contact' => $contact->id])}}" class="btn circle secondary">
                            <i class="fas fa-pen"></i>
                </a>
                <form method="POST" action="{{route('contacts.destroy', ['contact' => $contact->id])}}">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="ml-2 btn circle red dark-1">
                                <i class="fas fa-trash"></i>
                            </button>
                </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/contacts/search.blade.php
@extends('template.app')

@section('title', 'Rechercher - Contact')

@section('contenu')
<div class="card">
    <div class="card-header">Rechercher un contact</div>
    <div class="card-content">
        <form class="form-material" method="POST" action="{{route('contacts.update', ['contacts' => $contact->id])}}">
            @method('PUT')
            @csrf
            <div class="grix xs1">
                <div class="form-field">
                    <input type="text" id="name" name="name" class="form-control" value="{{$contact->name}}" />
                    <label for="title">Par prenom</label>
                </div>
                <div class="form-field">
                    <input type="text" id="lastname" name="lastname" class="form-control" value="{{$contact->name}}" />
                    <label for="title">Par nom</label>
                </div>
            </div>
            <button type="submit" class="btn press secondary">Rechercher</button>
        </form>
    </div>
</div>
@endsection

resources/views/template/app.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>@yield('title')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Import font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@0.4.2/dist/css/axentix.min.css" />
  </head>

  <body class="layout">
    <header>
      <nav class="navbar primary">
        <a href="#" target="_blank" class="navbar-brand">TP Crud Contacts</a>
        <div class="navbar-menu ml-auto">
          <a class="navbar-link" href={{route('contacts.index')}}>Mes Contacts</a>
          <a class="navbar-link" href={{route('contacts.create')}}>Créer</a>
          <a class="navbar-link" href={{route('contacts.search')}}>Rechercher</a>
        </div>
      </nav>
    </header>

    <main>
    @yield('contenu')
    </main>

    <footer class="footer primary">
      Copyright © 2019 - Example
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/axentix@0.4.2/dist/js/axentix.min.js"></script>
  </body>
</html>